version: '3.4'


services:
    hdfsname:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.8.1
        hostname: hdfsname
        command: name
        environment:
            - HADOOP_MASTER_ADDRESS=hdfsname
        ports:
            - 50070:50070
        volumes:
            - hdfsname:/data/hdfs
        deploy:
            placement:
                constraints:
                    - node.role == manager

    hdfsdata1:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.8.1
        command: data
        depends_on:
            - hdfsname
        environment:
            - HADOOP_MASTER_ADDRESS=hdfsname
        volumes:
            - hdfsdata1:/data/hdfs
        deploy:
            placement:
                constraints:
                    - node.labels.hdfs == 1

    hdfsdata2:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.8.1
        command: data
        depends_on:
            - hdfsname
        environment:
            - HADOOP_MASTER_ADDRESS=hdfsname
        volumes:
            - hdfsdata2:/data/hdfs
        deploy:
            placement:
                constraints:
                    - node.labels.hdfs == 2

    hdfsdata3:
        image: quay.io/geomesa/hdfs:geomesa-1.3.2-accumulo-1.8.1
        command: data
        depends_on:
            - hdfsname
        environment:
            - HADOOP_MASTER_ADDRESS=hdfsname
        volumes:
            - hdfsdata3:/data/hdfs
        deploy:
            placement:
                constraints:
                    - node.labels.hdfs == 3

    zookeeper:
        image: zookeeper:3.3
        hostname: zookeeper
        ports:
            - 2181:2181
        volumes:
            - zookeeper:/data
        deploy:
            placement:
                constraints:
                    - node.role == manager

    accumulomaster:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.8.1
        command: master --auto-init
        environment:
            HADOOP_MASTER_ADDRESS: hdfsname
            ZOOKEEPERS: zookeeper
            ACCUMULO_PASSWORD: IAccumulateMesas
        depends_on:
            - zookeeper
        deploy:
            placement:
                constraints:
                    - node.role == manager

    accumulomonitor:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.8.1
        command: monitor
        environment:
            HADOOP_MASTER_ADDRESS: hdfsname
            ZOOKEEPERS: zookeeper
        ports:
            - 9995:9995
            - 50095:50095
        depends_on:
            - zookeeper
            - accumulomaster
        deploy:
            placement:
                constraints:
                    - node.labels.geoserver != true

    accumulotserver:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.8.1
        command: tserver
        environment:
            HADOOP_MASTER_ADDRESS: hdfsname
            ZOOKEEPERS: zookeeper
        depends_on:
            - zookeeper
            - accumulomaster
        deploy:
            mode: global
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.labels.geoserver != true

    geoserver:
        image: quay.io/geomesa/geoserver:geomesa-1.3.2-accumulo-1.8.1
        ports:
            - 9090:9090
        volumes:
            - geoserver:/opt/tomcat/webapps/geoserver/data
        deploy:
            placement:
                constraints:
                    - node.labels.geoserver == true

volumes:
    hdfsname:
        driver: cloudstor:aws
        driver_opts:
            backing: relocatable
            size: 1
    hdfsdata1:
        driver: cloudstor:aws
        driver_opts:
            backing: relocatable
            size: 20
    hdfsdata2:
        driver: cloudstor:aws
        driver_opts:
            backing: relocatable
            size: 20
    hdfsdata3:
        driver: cloudstor:aws
        driver_opts:
            backing: relocatable
            size: 20
    zookeeper:
        driver: cloudstor:aws
        driver_opts:
            backing: relocatable
            size: 1
    geoserver:
        driver: cloudstor:aws
        driver_opts:
            backing: relocatable
            size: 1
